# http://localhost:8080/h2-console/

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./db/activity-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      # validate - will apply flyway migrations on startup      
      
ru:
  activity:
    db:
      populate: false
      